### ISSUE TITLE
Block classes

### ISSUE THREAD

**Issue by dags-** [Conquest-Reforged/ReforgedMod#1]
I think all the block classes in Core's `..block.` package, and everything under `..block.standard.` package can be moved to the Blocks module.

Might also be nice to organise into groups where possible/logical (preferably with no greater depth than one package). Example:
```
blocks/
blocks/Cube.java
blocks/Slab.java
blocks/arch/SmallArch.java
blocks/arch/BigArch.java
blocks/window/SmallWindow.java
blocks/window/BigWindow.java
```

**Comment by HIPPOKLEIDES** [comment]
Moved all those to the blocks module and got them organized into groups. Should look a lot cleaner now
