### ISSUE TITLE
OBJ models

### ISSUE THREAD

**Issue by dags-** [Conquest-Reforged/ReforgedMod#12]
Seems to be a bit different - might be as simple as providing a resourcelocation rather than string. Haven't tested yet.

Commented out line 20 in ClientInit (Blocks module)

**Comment by dags-** [comment]
Looks like we just need to add `"loader": "forge:obj"` to whatever json is specifying the model, so
```json
"defaults": {
    "loader": "forge:obj",
    "model": "conquest:block/lantern_large.obj",
    "textures": {
        "particle": "minecraft:block/iron_block"
    }
},
```

Source: [here](https://github.com/HIPPOKLEIDES/ConquestReforgedBlocksTest/blob/cf4d3b236aea948faee0ac5d723c0f9b487dc731/src/main/resources/assets/conquest/blockstates/ship_lantern.json)

I'll leave this open until tested and working

**Comment by HIPPOKLEIDES** [comment]
Doesn't seem to work as forge blockstates aren't working as they used to and blockstates require either "variants" or "multipart", which don't seem to be capable of taking OBJs.

Looks like there's a new system. Not sure if it's still in the works. https://github.com/MinecraftForge/MinecraftForge/tree/1.15.x/src/test/resources/assets/new_model_loader_test

Tried it out, and it does manage to get rid of all the errors, but when it comes to actually rendering the model, it don't quite work (as shown below)

![image](https://user-images.githubusercontent.com/31572523/71943581-f6d04380-3175-11ea-922f-358a902b0f78.png)

**Comment by dags-** [comment]
There was a commit 6 days ago that made some changes to the system so seems it's quite early-stages still:
https://github.com/MinecraftForge/MinecraftForge/commit/ca031ca33f1d8ca3f4375f6645aa91554632f23a

**Comment by dags-** [comment]
Loading the obj model from the forge example seems to work:
![](https://user-images.githubusercontent.com/4276064/72017439-93214580-325d-11ea-85ea-50dff8715463.png)
_ignore the texturing/coloring, I didn't copy that over_

I don't know too much about the format, but maybe the lantern model is in the wrong format or in a format that forge doesn't support?

**Comment by HIPPOKLEIDES** [comment]
Looks like forge no longer supports whatever format that OBJ was in (must have been made 3-4 years ago by now).

Anyway, seems to be working perfectly by just running the model through blender again.
