### ISSUE TITLE
Fourth level of Oak Wood Beam Vertical Quarter turns into Oak Wood Beam Wall instead of full block

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/ReforgedMod#21]
When placing a 4th **Oak Wood Beam Vertical Quarter** (or vertical slab or corner), the block turns into an **Oak Wood Beam Wall** instead of a full **Stripped Oak Wood** block.

If we follow other quarter/slab/corner blocks logic, filling the space turns the block into the "full" block version of the same texture, not the "Wall" version of said block.

![2020-03-16_14 42 18](https://user-images.githubusercontent.com/36215122/76790070-8278d880-6794-11ea-9a32-b45baf838ff4.png)

**Comment by dags-** [comment]
Please use the indev issue tracker linked in the patreon chat
