### ISSUE TITLE
Paintings, beds (with expected transparent textures) have white showing through

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/ReforgedMod#22]
Here's a couple pictures to show what i mean. Paintings have kind of an 8th-thick layer of canvas. White Bed's legs have some white showing...

Dunno if OptiFine would fix those or if the issue lies in CR resources...

![2020-03-16_14 56 10](https://user-images.githubusercontent.com/36215122/76791113-8e659a00-6796-11ea-9ab8-cf61fb2db032.png)
![2020-03-16_14 58 05](https://user-images.githubusercontent.com/36215122/76791114-8f96c700-6796-11ea-8f87-4d403fd4f76c.png)

**Comment by dags-** [comment]
Are these all vanilla paintings & beds? Pretty sure transparency isn't supported on the vanilla paintings, possibly not for beds either.

We might be able to fix both, not sure
