### ISSUE TITLE
Mirror's collision box is a full block

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/ReforgedMod#23]
The mirror's (conquest:mirror) collision box is a full block while the block itself is an 8th vertical-slab 3D model. In a cramped space, this kinda causes movement issues cuz you need to circle around the big invisible space. Not idea for narrow hallways and rooms.

Collision box should be the same 8th vertical-slab as the 3D model.

![2020-03-20_18 21 55](https://user-images.githubusercontent.com/36215122/77210709-0950ec80-6ad8-11ea-9484-a3af422b3853.png)

**Comment by HIPPOKLEIDES** [comment]
Good catch! It was an easy fix.
In the future though, please leave reports/issues at https://github.com/Conquest-Reforged/Indev/issues
