### ISSUE TITLE
Rope on the ground comes with rails texture

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/ReforgedMod#24]
Rope on the ground is displayed with rails texture...

![2020-03-20_23 51 58](https://user-images.githubusercontent.com/36215122/77218825-e6d5c800-6b05-11ea-89d3-ae7ee1583ef5.png)

**Comment by HIPPOKLEIDES** [comment]
You're probably using the regular Conquest resource-pack rather than the Conquest Reforged resourcepack (download/github page is in the patron files channel). 

In the future, please leave reports/issues at https://github.com/Conquest-Reforged/Indev/issues

**Comment by SamMadeChannel** [comment]
@HIPPOKLEIDES do i need to just download the CRRP repo in a zip file and drop it in ,minecraft/resourcepacks? That doesnt seems to load in-game atm...

**Comment by HIPPOKLEIDES** [comment]
You need to extract it from the zip file. Within the zip file, the resourcepack is nested within another folder. When you extract it from the zip file, do check whether the resourcepack is nested within any extra folders as well.

**Comment by SamMadeChannel** [comment]
Ah now it works great! Thanks a lot!
